### ISSUE TITLE
ウインドウのアイコンの変更について

### ISSUE THREAD

**Issue by Asura-Works** [kujirahand/tkeasygui-python#106]
こんにちは。
書籍「Pythonでつくるデスクトップアプリ」を買ってTkEasyGUIを知りました。
とても便利ではじめてのデスクトップアプリ開発も楽しんでいます。

ところで、Windowにアイコンを指定しているのですが、アイコンが変更されません。
まだ未実装なのでしょうか。
変更できるようになると有り難いです。

**Comment by lanius412** [comment]
Version 1.0.16 現在、アイコンの指定は未実装です。

#104 でマージされましたので、次期Version で使えるようになるかと思います。

現在Versionで試したいのであれば、次のどちらかから使用できます。
- インストールしているパッケージのwidgets.py をまるごと置き換える
   https://github.com/lanius412/tkeasygui-python/blob/set-window-icon/TkEasyGUI/widgets.py
- 私のrepositoryのブランチを指定してパッケージインストールする
  https://github.com/lanius412/tkeasygui-python/tree/set-window-icon

```py
import TkEasyGUI as eg

ICON = "./logo.png"

window = eg.Window("", layout = [[]], icon = ICON)

while window.is_alive():
  if window.read()[0] == eg.WIN_CLOSED:
    break
```

**Comment by Asura-Works** [comment]
情報ありがとうございます。
試させていただきますm(_ _)m

**Comment by kujirahand** [comment]
v1.0.17 で反映されました。
https://github.com/kujirahand/tkeasygui-python/releases/tag/1.0.17
