### ISSUE TITLE
マウスカーソルの変更について

### ISSUE THREAD

**Issue by Asura-Works** [kujirahand/tkeasygui-python#107]
少しデザインリッチにしたくて画像をボタン替わりにしようと画策しています。

Imageにenable_events=Trueを指定してイベントを仕込むことはできるのですが、マウスをあてたときにマウスカーソルが変わらないため視覚的に分かりづらいと感じました。

マウスカーソルを指定できるようにして頂けると助かります。
次期バージョンアップにぜひよろしくお願い致します。

**Comment by kujirahand** [comment]
Elementに set_cursor というメソッドを追加してみました。
下記のように、指定できます。
https://github.com/kujirahand/tkeasygui-python/commit/88417198745cc4f5b19400a2f3dcbaad20830e55
次のバージョン1.0.17以降で利用できるようになります。

**Comment by Asura-Works** [comment]
ありがとうございましたm(_ _)m
