### ISSUE TITLE
[Feature]: need justification

### ISSUE THREAD

**Issue by Seal-byte** [kujirahand/tkeasygui-python#108]
初めまして
いつも便利に使わせて頂いております。
ボタン位置の関係でpysimpleguiで言うjustificationが欲しいです。
padや何やらで努力はしているのですがどれもウィンドウサイズを
いじったりするとどうしても崩れてしまい・・・
あまり優先度は高くないかと思いますが、どこかで搭載をご一考頂けると嬉しいです。

お体を大切に末永く開発を続けて頂けますようお祈り申し上げます。

**Comment by kujirahand** [comment]
要望ありがとうございます。
下記の中央寄せや右寄せですよね。
https://docs.pysimplegui.com/en/latest/cookbook/original/justification_alignment/
調べて見ます

**Comment by kujirahand** [comment]
v1.0.18 で対応しました！これは便利ですね。
https://github.com/kujirahand/tkeasygui-python/releases/tag/1.0.18
良い提案をありがとうございました。
