### ISSUE TITLE
To support Window. return_keyboard_events and Window. enable_key_events

### ISSUE THREAD

**Issue by Ta2S** [kujirahand/tkeasygui-python#16]
windows11+Python3.12.2+PySimpleGUI4.60から、TkEasyGUIに移行できるかチャレンジしています。
Spaceキー、Sキー、ESCキーで操作するプログラムを移行しようとしているのですが、キー操作入力を認識してくれません。
キー操作入力には、現在のバージョンでは対応していないのでしょうか？
return_keyboard_events=True　もしくは　event, values = window.read() を修正することで、対応するのでしょうか？

**Comment by kujirahand** [comment]
確かに、PySimpleGUIでは、enable_events=Trueにするだけで、Multilneでイベントが発生するようですね。
下記のように、enable_key_events=Trueにすることで、キーイベントが発生するようになります。

```
window = eg.Window("タイトル", layout=[
    [eg.Multiline("100\n200", key="-input-", size=(50, 10), enable_events=True, enable_key_events=True)],
])
```

**Comment by Ta2S** [comment]
Multilneではなくて、修正中の抜粋ですが、こんな感じのキー入力イベント処理です。
昔Basicをかじったことがある程度のPythonプログラミングを独自学習している初心者で、Tkinterが理解できなくて・・・、表現もうまくできず、すみません。
4000ｘ3000以上の高解像度のUSBカメラで、検査対象のシートの写真を撮影しリサイズして表示し、カメラ・パソコン等の条件設定や、検査範囲のトリミング設定等を行う、初期設定ファイル作成プログラムを修正しています。
Spaceキーコードが入力されると、再撮影し、更新するプログラムです。
検査プログラムでは、Pushスイッチを押すと、Spaceキーコードのみ入力されるスイッチを利用した、1プッシュで1シートの異物を検査する、簡単操作を目指しており、同じような操作で初期設定ファイル作成プログラムも操作できるようにしています。

layout = [
    [TK.Frame('', [
        [TK.Image(size=(SY1, SX1),data=cv2.imencode('.png', frame_resized)[1].tobytes(), key='-IMAGE-')], ], key='-FRAME1-'),
     TK.Frame('', [
         [TK.Text('●画像更新：[ＰＵＳＨ(スペース)]キーを押してください')],
         [TK.Text('●設定保存：[Ｓ]キーを押してください')],
         [TK.Text('●終了　　：[ＥＳＣ]キーを押してください')],　・・・以降Sliderで設定

window = TK.Window('シート検査Setting', layout, enable_events=True, enable_key_events=True, size=(DY1, DX1),
                   modal=True, grab_anywhere=False, grab_anywhere_using_control=False,
                   keep_on_top=True, font=('Helvetica', FONT1), resizable=False,
                   finalize=True)
window.maximize()
window.refresh()

while True:
    print_camera_properties(cap)
    ut_now = datetime.datetime.now()
    print(ut_now, 'イベント入力待ち')
    event, values = window.read()
    ut_now = datetime.datetime.now()
    print(ut_now, event, values)
    if event == TK.WIN_CLOSED: # 画面を閉じる「Ｘ」ボタンが押されたら、ループを抜けてソフト終了
        break
    elif event == 'Escape:27': # 「ESC」キーが押されたら、ループを抜けてソフト終了
        break
    elif event == 'SLIDER_DSP': # FullHD、HDの選択で、ウィンドウ等のサイズを変更
        if values['SLIDER_DSP'] == 0:
            DSP = 0
        elif values['SLIDER_DSP'] == 1:
            DSP = 1
        continue
    elif event == 's': # 「ｓ」キーが押されたら、環境設定をファイル保存

**Comment by Ta2S** [comment]
投稿したら、左のスペースが消えてしまいました。読みにくくてすみません。
enable_events=True, enable_key_events=Trueへの置き換えをしましたが、Spaceキー、ｓキー、ESCキーを認識できませんでした。
よろしくお願いします。

**Comment by kujirahand** [comment]
この後、最新版をアップロードしますが、サンプルが不完全でしたので、微修正して、以下のようにして動くようしました。

```py
import TkEasyGUI as eg
#import PySimpleGUI as eg
layout = [
    [eg.Frame('', [[eg.Image(size=(300,300))],], key='-FRAME1-'),
     eg.Frame('', [
         [eg.Text('●画像更新：[ＰＵＳＨ(スペース)]キーを押してください')],
         [eg.Text('●設定保存：[Ｓ]キーを押してください')],
         [eg.Text('●終了　　：[ＥＳＣ]キーを押してください')],
     ])],
     [eg.Multiline(size=(40, 15), key="-text-")],
]

window = eg.Window('test', layout,
                   # enable_key_events=True,
                   return_keyboard_events=True,
                   modal=True, grab_anywhere=False, grab_anywhere_using_control=False,
                   keep_on_top=True, font=('Helvetica', 18), resizable=False,
                   finalize=True)
while True:
    event, values = window.read()
    print(f"[{event}]", values)
    # 画面を閉じる「Ｘ」ボタンが押されたら、ループを抜けてソフト終了
    if event == eg.WIN_CLOSED:
        break
    # 「ESC」キーが押されたら、ループを抜けてソフト終了
    elif event == 'Escape:27' or event == "Escape:889192475":
        break
    # 「ｓ」キーが押されたら、環境設定をファイル保存
    elif event == 's':
        eg.popup("saved")
```

**Comment by kujirahand** [comment]
v0.2.45でサポートしました。
https://pypi.org/project/TkEasyGUI/0.2.45/
