### ISSUE TITLE
Sliderについて

### ISSUE THREAD

**Issue by Ta2S** [kujirahand/tkeasygui-python#23]
キー入力への対処、ありがとうございました。0.2.45で動作できるようになりました。

Sliderについて、報告させていただきます。

PySimpleGUIのように、スライダーの値を表示するオプションはありますでしょうか？

disable_number_display=Falseとしても値が表示されず、

[TK.Text('フォーカス設定 　-40＜＞+40　：IMX298は無効')],
[TK.Slider(range=(FCS-40, FCS+40), default_value=FCS, resolution=10, orientation='h', key='SLIDER_FCS', enable_events=True),TK.Text(FCS)],
のように「TK.Text(FCS)」を追加するだけでは初期値表示から更新できなくて・・・。

あと、resolution=10は効いていないようで、左右をクリックすると1ずつ増減し、掴んで動かすと小数点以下の数値が設定され、左右をクリックすると小数点以下を維持したまま1ずつ増減します。

変更した結果は0.2.45で保存できるようになったのですが、今の値が何なのかは、VSCodeで見て確認チェックしています。

すみませんが、オプション設定が違うなどの対処方法があれば、公開していただけないでしょうか。
よろしくお願いします。

**Comment by kujirahand** [comment]
ご指摘ありがとうございます。
この後、最新版で反映させようと思います。

**Comment by kujirahand** [comment]
v0.2.47 で disable_number_displayを実装しました。

なお、現在、Sliderで使えるオプションの一覧は
https://github.com/kujirahand/tkeasygui-python/blob/main/docs/TkEasyGUI/widgets-py.md#slider
で確認できます。

**Comment by Ta2S** [comment]
ｖ0.2.47ありがとうございます。
無事、必要とするSlider機能を再現できるようになりました。
ありがとうございました。
