### ISSUE TITLE
locationについて

### ISSUE THREAD

**Issue by Ta2S** [kujirahand/tkeasygui-python#24]
locationについて、報告させていただきます。

下記コードを使用し、USBカメラの初期設定＆プレスキャン中に、プログラムが動いていることがわかるように表示します。

# 起動中ウィンドウのレイアウトを定義
layout = [[TK.Text(' ')],[TK.Text(' ')],
          [TK.Text('    シート検査Setting起動中    ', font=('Helvetica', 30))],
          [TK.Text(' ')],[TK.Text(' ')]]
# タイトルバー無しの起動中ウィンドウを作成
window0 = TK.Window('Window Title', layout, no_titlebar=True, keep_on_top=True, modal=True, finalize=True)
window0.refresh() # 文字が表示されない時の対策

最初、左上の端に表示されたため、location='center' で画面中央に表示しようとしました。
すると、画面上下の中央には表示されたのですが左右は右にズレて表示され、location='center' を削除しても中央右ズレ表示のまま、location=(0,0)等を指定しても中央右ズレ表示のまま変わらなくなってしまいました。

メインの設定・保存画面も、中央右ズレの起動中ウィンドウの開始位置より、右下にズレて画面からはみ出して表示され、改善できません。
メインの設定・保存画面は、とりあえず全画面表示にすれば問題ないのですが、起動中ウィンドウを画面の任意の位置に表示する方法があれば、教えていただけないでしょうか。
よろしくお願いします。

**Comment by kujirahand** [comment]
最新、v0.2.49にて、Windowにlocation引数、および、set_location関数を実装しました。
https://github.com/kujirahand/tkeasygui-python/blob/main/docs/TkEasyGUI/widgets-py.md#windowset_location

**Comment by Ta2S** [comment]
表示位置の設定が問題なくできるようになりました。
v0.2.49ありがとうございました。
