### ISSUE TITLE
themeについて

### ISSUE THREAD

**Issue by Ta2S** [kujirahand/tkeasygui-python#33]
テーマカラー選択をプログラムに組み込むためのチェックを下記コードでしています。

#TkEasyGUIテーマカラーを設定できるようにする

import TkEasyGUI as sg

sg.theme('default') # 初期設定
window = sg.Window("Inch to cm", layout=[
    [sg.Text("Please select item:")],
    [sg.Listbox(
        ['default','winnative','clam','alt','classic','vista','xpnative'],
        default_values=["default"], enable_events=True,
        size=(20, 7), key="-listbox-")],
    [sg.Text("-", key="-result-")],
])
while True:
    event, values = window.read()
    print(event, values)
    if event == sg.WIN_CLOSED:
        break
    if event == "-listbox-":
        window["-result-"].update("/".join(values["-listbox-"]))
        sg.theme(values["-listbox-"])
        sg.popup_get_text('This is {}'.format(values["-listbox-"]))
        window.refresh()

window.close()

配色が、「無地」と「薄グレー」のような2配色しか表示されません。
初期設定の部分を変更しても、変わらないようです。

**Comment by Ta2S** [comment]
v0.2.49、windows11です。

**Comment by kujirahand** [comment]
#3 にて実装途中ですが、Tkinterのテーマは相当独特であることが分かり、難航しています。

現在のところ、できるだけOSデフォルトに近いテーマを選んで、なんとなく見栄えが良くなるように設定したところで止まっています。また、macOSなどでは、全くFrameの背景色が設定できないようです。

PySimpleGUIでは、Frameの上に描画用のキャンバスなどを配置して、配色が強制的に変更できるようにしているようですが、もう少し、機能が落ち着いてから実装すると、修正の手間がなくなるため、テーマの実装はしばらくお待ちください。

**Comment by kujirahand** [comment]
現在不完全である旨をドキュメントに追加します。
#3 と重複してしまいますので、こちらは閉じさせていただきます。
