### ISSUE TITLE
sg.Tableでヘッダ変更とヘッダサイズの問題について

### ISSUE THREAD

**Issue by montagne5641** [kujirahand/tkeasygui-python#54]
読み込んだcsvファイルをsg.Tableでテーブル表示したいのですが、 unknown option "-headingsと出て、空のテーブルのみが表示されます。コードは以下です。
（もし根本的な間違いをしておりましたら申し訳ございません）

import TkEasyGUI as sg
import pandas as pd

layout = [
    [sg.Text("計算結果")],
    [sg.Text("")],
    [sg.Text("データテーブル")],
    [sg.Table(values=[], headings=[], key='-table-',expand_x=True,expand_y=True,enable_events=True)],
    [sg.InputText(key="-FILE-",width=50), sg.FileBrowse(file_types=(("CSV Files", "*.csv"),))],    
    [sg.Button("読み込む")],
    [sg.Text("")]
]

window = sg.Window("test", layout, resizable=True, size=(500, 500),enable_events=True, finalize=True)

while True:
    event, values = window.read()

    if event == sg.WINDOW_CLOSED or event == "終了":
        break

    elif event == "読み込む":
        filename = values["-FILE-"]
        if filename:

            df = pd.read_csv(filename, delimiter=",",index_col=0, encoding='cp932')          

            df = pd.read_csv(filename, delimiter=",",index_col=None, encoding='cp932')     
            data_values = df.values.tolist()
            header_list = df.columns.tolist()
            window["-table-"].update(values=data_values, headings=header_list,expand_x=True,expand_y=True)

window.close()

**Comment by kujirahand** [comment]
貴重なレポートありがとうございます。
現状では、headingsをupdateで更新できないのです。
そこで、CSVファイルを読み込んだら、Windowを作り直すという方法で対処していたければと思います。
この点、修正できるように調査してみます。

**Comment by montagne5641** [comment]
kujirahandさま
ご確認いただき、また代替法をご教示いただき誠にありがとうございます。
ご指摘いただいた通り再度windowを作り直す形で対応出来ることを確認できました。
大変便利なツールです。今後とも何卒よろしくお願いいたします。

**Comment by kujirahand** [comment]
先ほどリリースしたv0.2.71でヘッダを更新できるようにしました。
Table生成時にmax_columns引数に指定した最大カラム数以下であれば更新可能です。

**Comment by montagne5641** [comment]
早速試させていただいたところ思った通りに更新でき非常に使い勝手が良くなりました！ありがとうございます！
併せてテーブルカラム数についてご相談がございます。
例えば以下のようにテーブルサイズよりもずっと多い数のカラムを表示させることを想定した場合、現行では1枚目のように「一部を大きく表示する」か2枚目のように「全体を小さく表示する」のどちらかしかできないように思います。例えば、横スクロールバーをつけて大きく表示したままスクロール確認できるようになったりすることは難しいでしょうか。

![image](https://github.com/kujirahand/tkeasygui-python/assets/99020374/9c362633-2edb-4ca8-ac20-36738398dd56)
![image](https://github.com/kujirahand/tkeasygui-python/assets/99020374/0be90fd5-9fc7-4d06-8b0c-15886ad86f4b)

**Comment by kujirahand** [comment]
修正に着手します。分かりやすくタイトルを変更させていただきました。

**Comment by kujirahand** [comment]
v0.2.73で水平報告のスクロールバーも実装しました。PySimpleGUIと合わせて、vertical_scroll_only=Falseを指定すると水平スクロールバーが表示されるようになります。また垂直スクロールバーが出なくなっていたので修正しました。
