### ISSUE TITLE
Columnのサイズを指定しても無視される問題

### ISSUE THREAD

**Issue by montagne5641** [kujirahand/tkeasygui-python#55]
お世話になります。
Columnでテーブルを含む複数カラムを作成する場合にサイズの指定を行ってもそれが反映されないように思います。

例）
            layout1 = [・・・]
            layout2 = [eg.Table(values=data_values, headings=header_list, key='-table-',expand_x=False,expand_y=True,enable_events=True,auto_size_columns=False,max_col_width=10)]]
            layout3= [・・・]
                
            #レイアウトをまとめる
            col1 = eg.Column(layout1, width=300)
            col2 = eg.Column(layout2, vertical_alignment="top", width=300)
            col3 = eg.Column(layout3, vertical_alignment="top", width=300)
            layout=[[col1,col2,col3]]

            window = eg.Window("test", layout, resizable=True, size=(1920, 1080),enable_events=True)

本当はTable自体の最大幅を指定したかったのですが、tableには全体幅を調整するパラメータが無い（はず）のため、代わりに同テーブルを含むColumn側で幅を調節しようと思いました。
ただ、上記のようにColumnで幅を指定しても反映されませんでした。
またwidthの部分をsize=()て指定しても同様でした。
Tableに含まれる列が20列程度あり、全部が表示される必要はなくColumnの幅に収まるものだけ表示されればよい（表示しきれないものはスクロールで対応）を考えているのですが、現状はColumnで幅を設定してもTableの幅が異常に横伸び表示されているような状況です。もしかしたら不具合と思い、共有させていただきます。

**Comment by kujirahand** [comment]
確認ありがとうございます。
今のところ、Columnにwidthを指定しても反映されません。
Column(TkinterのFrame)は配置後、自動リサイズが有効になっているからです。
とは言え、sizeやwidthを指定した場合には、自動リサイズをオフにする方が自然ですね。
size/widthを指定した時の処理を改良しようと思います。

**Comment by montagne5641** [comment]
ご確認いただきありがとうございます。
Columnのサイズ及び各カラム内に設置したテーブルやキャンバスの配置を整えて見栄えを調整するのに四苦八苦していたところでした。サイズで指定できるととても良いと思います。自動リサイズも使い方によっては便利ですね。

サイズに関する処で、テーブル自体のサイズを設定するのはやはり難しいでしょうか？pysimpleguiでもできなかったようで、某の制約があるようにも感じました。

![Screenshot_20240614-221112](https://github.com/kujirahand/tkeasygui-python/assets/99020374/8fb2ff27-2359-43f5-aad8-923bc68603ba)

**Comment by kujirahand** [comment]
@montagne5641 さま、パラメータをまとめてくださりありがとうございます！

Columnのsizeが反映されるように修正した最新版0.2.71をアップしました。
widthパラメータも指定できるようになっています。

また、Tableのsizeについては実現できるかどうかは、以下のIssuesで検証します。

- Tableでsizeが指定できるか検証する #58

Columnのsizeは有効になったため、一度、こちらのIssuesは解決ということで、Closeさせていただきます。
ご報告、および、ご提案ありがとうございました。
