### ISSUE TITLE
multilineにおけるautoscrollの実装

### ISSUE THREAD

**Issue by montagne5641** [kujirahand/tkeasygui-python#60]
たびたび失礼いたします。今後に向けた要望といたしまして、multilineにprint追記をしていき、最下段まで進んだら以降は一般的なログ表示（＝オートスクロール）される機能があるとよいと思いました。

pysimpleguiにおいてautoscrollに相当するものです。
https://docs.pysimplegui.com/en/latest/call_reference/tkinter/elements/multiline/

**Comment by kujirahand** [comment]
autoscroll便利ですね。機能を追加しようと思います。

**Comment by kujirahand** [comment]
v0.2.72 以降で使えるようになりました。

**Comment by montagne5641** [comment]
実装いただきありがとうございました。早速テストさせていただき、希望通り動作することを確認できました。大変感謝いたします。
