### ISSUE TITLE
Inputのsize指定

### ISSUE THREAD

**Issue by yuki1018** [kujirahand/tkeasygui-python#61]
綺麗なレイアウトを作成する上では必須の機能だと思います。
実装いただきたいです。

**Comment by kujirahand** [comment]
@yuki1018 とても良い提案ありがとうございます。
現在、widthで幅が指定できますが、sizeでも指定できるように修正しようと思います。

**Comment by kujirahand** [comment]
v0.2.72 以降で使えるようになりました。
