### ISSUE TITLE
カレンダー機能について

### ISSUE THREAD

**Issue by fleming35800** [kujirahand/tkeasygui-python#62]
はじめまして。PySimpleGUIに変わってこのような使いやすいパッケージを作っていただきありがとうございます。
PySimpleGUIを使用していた時にカレンダーの機能をよく使っていました。
今後カレンダー機能について実装の予定はございますでしょうか？

**Comment by kujirahand** [comment]
ご要望ありがとうございます！
カレンダー機能は、CalendarButtonのことでしょうか？
確かに便利ですね。近々実装しようと思います。

- (参考) https://naotoshisami.com/2022/01/pysimplegui-python-gui-calendar-button/
  - https://github.com/PySimpleGUI/PySimpleGUI/blob/master/DemoPrograms/Demo_Calendar.py
  - https://docs.pysimplegui.com/en/latest/call_reference/tkinter/elements/pre_defined_buttons/#calendarbutton

**Comment by kujirahand** [comment]
v0.2.73で実装しました✨
お試しください。

**Comment by fleming35800** [comment]
コメント頂きありがとうございます。
また実装も頂きましてありがとうございます。
迅速な対応に感謝です！！！
