### ISSUE TITLE
ウインドウを表示しているだけで1コア分のCPU使用率が100%にはりつく

### ISSUE THREAD

**Issue by hosiken** [kujirahand/tkeasygui-python#78]
バージョン: 1.0.2、Windows、Python 3.9.0 です。
シンプルにウインドウを表示するだけのコードでも、1コア分のCPU使用率が100%にはりついてしまいます。
file_viewer.py 自身およびそこから参照できるすべてのサンプルや、以下のシンプルなコードでも発生します。

```python
import TkEasyGUI as eg

layout = [
    [eg.Submit(button_text='ボタン')]
]

# セクション 2 - ウィンドウの生成
window = eg.Window('ウインドウ', layout)

# セクション 3 - イベントループ
while True:
    event, values = window.read()

    if event is None:
        print('exit')
        break

    if event == 'ボタン':
        break

# セクション 4 - ウィンドウの破棄と終了
window.close()
```

![image](https://github.com/user-attachments/assets/b7e0722a-11a7-4130-8cd3-d60d2bc81711)

![image](https://github.com/user-attachments/assets/2e7b426c-5e95-4479-b2fa-dc850e07aaae)

**Comment by kujirahand** [comment]
ご報告ありがとうございます。すぐ改善したいと思います。

**Comment by kujirahand** [comment]
v1.0.3で上記の問題対処しました。

**Comment by hosiken** [comment]
爆速の対応ありがとうございます! 無事直っていました。
![image](https://github.com/user-attachments/assets/ae9bfef8-e6e1-4dd6-9cc9-aae3638485ca)
