### ISSUE TITLE
Add Read-Only Mode to Combo Element

### ISSUE THREAD

**Issue by lanius412** [kujirahand/tkeasygui-python#87]
Combo Elementに対して、ユーザーの入力を無効化するreadonly modeの追加

PRしていいものかわからないので、forkしてreadonly追加したものを使用しています
```
pip3 install -e git+https://github.com/lanius412/tkeasygui-python
or
uv add git+https://github.com/lanius412/tkeasygui-python
```

https://github.com/lanius412/tkeasygui-python/blob/bd6b278a65539649daf377cc20fab2324a3be725/TkEasyGUI/widgets.py#L3139-#L3191

**Comment by kujirahand** [comment]
@lanius412 Read-Onlyモード、便利です！！ありがとうございます！

今後は、気軽にPRしてください！
とりあえず、ソースコードに取り込ませていただきました。

**Comment by lanius412** [comment]
マージありがとうございました！

> @lanius412 Read-Onlyモード、便利です！！ありがとうございます！
> 
> 今後は、気軽にPRしてください！ とりあえず、ソースコードに取り込ませていただきました。
