### ISSUE TITLE
Freeze when popup closed

### ISSUE THREAD

**Issue by lanius412** [kujirahand/tkeasygui-python#89]
閉じるボタン`X`でpopup windowを閉じた場合、
main windowでクリック等ができない

Windows, mac(Intel) 同様です

```python
import TkEasyGUI as eg

window = eg.Window("", layout=[[eg.Button('popup', key='-popup-')]])

while window.is_alive():
    event, values = window.read()
    if event == '-popup-':
        eg.popup('popup window')

```

**Comment by kujirahand** [comment]
@lanius412 なんと！全く気付きませんでした。すぐ直したいと思います。

**Comment by lanius412** [comment]
修正ありがとうございます。

ところで、Discord鯖は動いていますか？
READMEに記載のリンク切れてるみたいなので

**Comment by kujirahand** [comment]
Discordリンク切れてましたか・・・どうりで人が来ないはず・・・更新しました。
https://discord.gg/jB2ZZh2b
