### ISSUE TITLE
Radioのeventで最初のkeyしか返ってこないのは仕様でしょうか。

### ISSUE THREAD

**Issue by AkihikoTsurugi** [kujirahand/tkeasygui-python#92]
ラジオボタンを作成して、選択されたボタンのeventをwatchしていますが、どのボタンを押しても最初のkeyの値が返ってきます。

同じコードで、PySImpleGUIではキチンとボタン別のkeyがeventで上がってきます。

valueの値はきちんと更新されます。

今は、全てのRadioのkeyをwatchして、valueの中身で処理を変える方法で回避しています。

（例）
下記のようなラジオボタン２つのウィンドウを作成し、ラジオボタン「オプション１」を選択しても「オプション２」を選択してもeventがoption1で戻ってくるようです。

PySimpleGUIでは、きちんとoption2が戻ってきました。

valueの値は更新されています。
{'event_type': 'change', 'event': ('PY_VAR0', '', 'write'), 'option1': False, 'option2': True}

# import PySimpleGUI as sg
import TkEasyGUI as sg

# レイアウトの定義
layout = [
    [sg.Text('選択してください:')],
    [sg.Radio('オプション 1', group_id="RADIO1", key='option1', enable_events=True)],
    [sg.Radio('オプション 2', group_id="RADIO1", key='option2', enable_events=True)],
    [sg.Button('終了')]
]

# ウィンドウの作成
window = sg.Window('ラジオボタンの例', layout)

# イベントループ
while True:
    event, values = window.read()
    print(event)
    print(values)
    
    # ウィンドウが閉じられた場合
    if event == sg.WIN_CLOSED or event == '終了':
        break
    
    elif event == "option1":
        sg.popup("オプション 1 が選択されました")
        print("オプション 1 が選択されました")
    elif event == "option2":
        sg.popup("オプション 2 が選択されました")
        print("オプション 2 が選択されました")

# ウィンドウの終了
window.close()

**Comment by kujirahand** [comment]
ご報告ありがとうございました！すぐに修正します。

**Comment by kujirahand** [comment]
緊急度が高いバグでしたので、すぐにアップデートしました。
v1.0.13で修正されました✨
