### ISSUE TITLE
ラジオボタンとチェックボックスの併用時に、ラジオボタンのeventがうまく出てくれません。

### ISSUE THREAD

**Issue by AkihikoTsurugi** [kujirahand/tkeasygui-python#93]
ラジオボタンのeventへのご対応ありがとうございました。

で、追加なのですが…

チェックボックスが併用されると、ラジオボタンのeventがうまく拾えません。
チェックボックスを全て外すと、うまくラジオボタンのeventが拾えます。

チェックボックス以降のラジオボタンは、きちんとeventを出してくれます。

PySimpleGUIだと問題なく、チェックボックスにチェックがあってもラジオボタンのeventを出してくれます。

以下検証したコードです。

### import PySimpleGUI as sg
import TkEasyGUI as sg

layout = [
    [sg.Text('選択してください:')],
    [sg.Radio('オプション 1', group_id="RADIO1", key='option1', enable_events=True, default=True)],
    [sg.Checkbox('チェックボックス', key='check1', enable_events=True),
              sg.Checkbox('チェックボックス2', key='check2', enable_events=True)],
    [sg.Radio('オプション 2', group_id="RADIO1", key='option2', enable_events=True)],
    [sg.Button('終了')]
]

window = sg.Window('ラジオボタンの例', layout)

while True:
    event, values = window.read()
    print(event)
    print(values)
    
    # ウィンドウが閉じられた場合
    if event == sg.WIN_CLOSED or event == '終了':
        break
    
    elif event == "option1":
        sg.popup("オプション 1 が選択されました")
        print("オプション 1 が選択されました")
    elif event == "option2":
        sg.popup("オプション 2 が選択されました")
        print("オプション 2 が選択されました")

window.close()

**Comment by kujirahand** [comment]
イベントが発生したとき、変数valuesの値がおかしいということでしょうか。検証します。

```py
# import PySimpleGUI as sg
import TkEasyGUI as sg

layout = [
    [sg.Text('選択してください:')],
    [sg.Radio('オプション 1', group_id="RADIO1", key='option1', enable_events=True, default=True)],
    [sg.Checkbox('チェックボックス', key='check1', enable_events=True),
              sg.Checkbox('チェックボックス2', key='check2', enable_events=True)],
    [sg.Radio('オプション 2', group_id="RADIO1", key='option2', enable_events=True)],
    [sg.Button('終了')]
]
window = sg.Window('ラジオボタンの例', layout)
while True:
    event, values = window.read()
    print("@@@", event, "values=", values)
    # ウィンドウが閉じられた場合
    if event == sg.WIN_CLOSED or event == '終了':
        break
    elif event == "option1":
        # sg.popup("オプション 1 が選択されました")
        print("オプション 1 が選択されました")
    elif event == "option2":
        # sg.popup("オプション 2 が選択されました")
        print("オプション 2 が選択されました")

window.close()
```

**Comment by kujirahand** [comment]
分かりました。RadioのdefaultがTrueのときで、値をTrueに変更するときに不完全なイベントを送出してしまうようですね。修正します。

**Comment by kujirahand** [comment]
v1.0.16で解決しました！

```
pip install -U TkEasyGUI
```

最新版をお試しください。

**Comment by AkihikoTsurugi** [comment]
ご対応ありがとうございます。


　1.0.16にて試してみました。


　が、私の思う挙動とは異なりました。




　後述のコードにて検証しています。

　※　'radio_n_chekbox.pyをPySimpleGUIでも動くようにcheckbox側のgroupidを削除しkeyを追加しています。



'macOS'をクリック（チェック）した際のそれぞれの挙動



PySimpleGUI
　→eventでクリックした'mac’を上げてくれる。
　@@@ mac values= {'win': False, 'mac': True, 'ubuntu': False, 'others': False, 'dog': True, 'cat': False, 'rabit': False}



TkEasyGUI
　→eventでcheck box側の 'dog'を上げてくる。

　@@@ dog values= {'win': False, 'mac': True, 'ubuntu': False, 'others': False, 'dog': True, 'cat': False, 'rabit': False, 'OS': 'mac', 'event_type': 
'change'}



　私の意図する動きは、PySimpleGUIの方でして、必ずアクションしたもののボタンのkeyがeventで上がって欲しいのですが、そもそもの考え方が異なるのでしょうか。

**Comment by AkihikoTsurugi** [comment]
ご対応ありがとうございます。


　1.0.16にて試してみました。


　が、私の思う挙動とは異なりました。




　後述のコードにて検証しています。

　※　'radio_n_chekbox.pyをPySimpleGUIでも動くようにcheckbox側のgroupidを削除しkeyを追加しています。



'macOS'をクリック（チェック）した際のそれぞれの挙動



PySimpleGUI
　→eventでクリックした'mac’を上げてくれる。
　@@@ mac values= {'win': False, 'mac': True, 'ubuntu': False, 'others': False, 'dog': True, 'cat': False, 'rabit': False}



TkEasyGUI
　→eventでcheck box側の 'dog'を上げてくる。

　@@@ dog values= {'win': False, 'mac': True, 'ubuntu': False, 'others': False, 'dog': True, 'cat': False, 'rabit': False, 'OS': 'mac', 'event_type': 
'change'}



　私の意図する動きは、PySimpleGUIの方でして、必ずアクションしたもののボタンのkeyがeventで上がって欲しいのですが、そもそもの考え方が異なるのでしょうか。






```
``import TkEasyGUI as eg
## import PySimpleGUI as eg

layout = [
    [
        eg.Frame(
            "OS:",
            layout=[
                [
                    eg.Radio(
                        "Windows",
                        group_id="OS",
                        key="win",
                        enable_events=True,
                        default=True,
                    )
                ],
                [eg.Radio("macOS", group_id="OS", key="mac", enable_events=True)],
                [eg.Radio("Ubuntu", group_id="OS", key="ubuntu", enable_events=True)],
                [eg.Radio("Others", group_id="OS", key="others", enable_events=True)],
            ],
        )
    ],
    [
        eg.Frame(
            "Animals",
            layout=[
                [
                    eg.Checkbox(
                        "Dog", key="dog", enable_events=True, default=True
                    )
                ],
                [eg.Checkbox("Cat", key="cat", enable_events=True)],
                [eg.Checkbox("Rabit", key="rabit", enable_events=True)],
            ],
        )
    ],
    [eg.Button("OK"), eg.Button("Cancel")],
]
window = eg.Window("Radio and Checkbox samples:", layout)
while True:
    event, values = window.read()
    print("@@@", event, "values=", values)
    if event == "OK":
        os = values["OS"]
        animals = ",".join(values["animals"])
        eg.print(f"You selected: {os} and [{animals}]")
        break
    if event == "Cancel":
        break
window.close()``
```

**Comment by kujirahand** [comment]
@AkihikoTsurugi さま、失礼しました。
ラジオとチェックボックスが混乱する問題を修正しました。
次のバージョンで反映されます。

**Comment by kujirahand** [comment]
v1.0.20で修正しました
https://github.com/kujirahand/tkeasygui-python/releases/tag/1.0.20

**Comment by AkihikoTsurugi** [comment]
ご対応ありがとうございました。

動作確認いたしました。

<(_ _)>
