### ISSUE TITLE
So this is a imitation to the PySimpleGUI?

### ISSUE THREAD

**Issue by yancj9ya** [kujirahand/tkeasygui-python#94]
the code is too many part similarity to PySimpleGUI!
but anyway you doing good
casue PySimpleGUI is not for free now

**Comment by kujirahand** [comment]
@yancj9ya Thank you for your comment.
This project started as a result of PySimpleGUI becoming a paid tool.
I hope to create GUI applications more freely and easily with Python.
Thank you for your continued support.
